# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'networks.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import pickle
import socket
from dataclasses import dataclass
import time
from numpy import array

@dataclass
class question:
    num: int
    Q: str
    a: str
    b: str
    c: str
    d: str
    ans: str

rows, cols = (5, 5)
arr = array([['----------------------------------------------------------------------------------', '----------', '----------', '----------', '----------'], ['----------------------------------------------------------------------------------', '----------', '----------', '----------', '----------'], ['----------------------------------------------------------------------------------', '----------', '----------', '----------', '----------'], ['----------------------------------------------------------------------------------', '----------', '----------', '----------', '----------'], ['----------------------------------------------------------------------------------', '----------', '----------', '----------', '----------']])

s = socket.socket()

port = 12000

s.connect(('127.0.0.1', port))
print(s.recv(1024).decode())

for i in range(5):

    data = s.recv(4096)
    dataVariable = pickle.loads(data)
    k = str('Q' + str(i+1) + '- ' + dataVariable.Q)
    arr[i][0] = k
    print(arr[i][0])
    l = 'a- ' + dataVariable.a
    arr[i][1] = l
    m = 'b- ' + dataVariable.b
    arr[i][2] = m 
    n = 'c- ' + dataVariable.c
    arr[i][3] = n
    o = 'd- ' + dataVariable.d
    arr[i][4] = o
    time.sleep(0.2)

s.close()


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(977, 868)
        Dialog.setStyleSheet("")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(40, 60, 471, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(70, 90, 261, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(70, 120, 471, 31))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(70, 150, 471, 31))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(70, 180, 471, 31))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(420, -10, 121, 71))
        font = QtGui.QFont()
        font.setPointSize(27)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(70, 280, 471, 31))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(70, 310, 471, 31))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(70, 340, 471, 31))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(70, 250, 261, 31))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setGeometry(QtCore.QRect(40, 220, 471, 31))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(Dialog)
        self.label_12.setGeometry(QtCore.QRect(70, 440, 471, 31))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(Dialog)
        self.label_13.setGeometry(QtCore.QRect(70, 470, 471, 31))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(Dialog)
        self.label_14.setGeometry(QtCore.QRect(70, 500, 471, 31))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(Dialog)
        self.label_15.setGeometry(QtCore.QRect(70, 410, 261, 31))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(Dialog)
        self.label_16.setGeometry(QtCore.QRect(40, 380, 471, 31))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(Dialog)
        self.label_17.setGeometry(QtCore.QRect(70, 730, 261, 31))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(Dialog)
        self.label_18.setGeometry(QtCore.QRect(70, 790, 471, 31))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(Dialog)
        self.label_19.setGeometry(QtCore.QRect(70, 630, 471, 31))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(Dialog)
        self.label_20.setGeometry(QtCore.QRect(70, 660, 471, 31))
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(Dialog)
        self.label_21.setGeometry(QtCore.QRect(40, 700, 471, 31))
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(Dialog)
        self.label_22.setGeometry(QtCore.QRect(70, 600, 471, 31))
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(Dialog)
        self.label_23.setGeometry(QtCore.QRect(40, 540, 471, 31))
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(Dialog)
        self.label_24.setGeometry(QtCore.QRect(70, 570, 261, 31))
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(Dialog)
        self.label_25.setGeometry(QtCore.QRect(70, 760, 471, 31))
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(Dialog)
        self.label_26.setGeometry(QtCore.QRect(70, 820, 471, 31))
        self.label_26.setObjectName("label_26")
        self.graphicsView = QtWidgets.QGraphicsView(Dialog)
        self.graphicsView.setGeometry(QtCore.QRect(320, 330, 281, 281))
        self.graphicsView.setStyleSheet("background-image: url(:/newPrefix/D:/Downloads/WhatsApp Image 2022-06-01 at 1.31.35 PM (1).jpeg);")
        self.graphicsView.setObjectName("graphicsView")
        self.graphicsView.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.label_9.raise_()
        self.label_10.raise_()
        self.label_11.raise_()
        self.label_12.raise_()
        self.label_13.raise_()
        self.label_14.raise_()
        self.label_15.raise_()
        self.label_16.raise_()
        self.label_17.raise_()
        self.label_18.raise_()
        self.label_19.raise_()
        self.label_20.raise_()
        self.label_21.raise_()
        self.label_22.raise_()
        self.label_23.raise_()
        self.label_24.raise_()
        self.label_25.raise_()
        self.label_26.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Online Quiz"))
        self.label.setText(_translate("Dialog", arr[0][0]))
        self.label_2.setText(_translate("Dialog", arr[0][1]))
        self.label_3.setText(_translate("Dialog", arr[0][2]))
        self.label_4.setText(_translate("Dialog", arr[0][3]))
        self.label_5.setText(_translate("Dialog", arr[0][4]))
        self.label_6.setText(_translate("Dialog", "QUIZ"))
        self.label_7.setText(_translate("Dialog", arr[1][0]))
        self.label_8.setText(_translate("Dialog", arr[1][1]))
        self.label_9.setText(_translate("Dialog", arr[1][2]))
        self.label_10.setText(_translate("Dialog", arr[1][3]))
        self.label_11.setText(_translate("Dialog", arr[1][4]))
        self.label_12.setText(_translate("Dialog", arr[2][0]))
        self.label_13.setText(_translate("Dialog", arr[2][1]))
        self.label_14.setText(_translate("Dialog", arr[2][2]))
        self.label_15.setText(_translate("Dialog", arr[2][3]))
        self.label_16.setText(_translate("Dialog", arr[2][4]))
        self.label_17.setText(_translate("Dialog", arr[3][0]))
        self.label_18.setText(_translate("Dialog", arr[3][1]))
        self.label_19.setText(_translate("Dialog", arr[3][2]))
        self.label_20.setText(_translate("Dialog", arr[3][3]))
        self.label_21.setText(_translate("Dialog", arr[3][4]))
        self.label_22.setText(_translate("Dialog", arr[4][0]))
        self.label_23.setText(_translate("Dialog", arr[4][1]))
        self.label_24.setText(_translate("Dialog", arr[4][2]))
        self.label_25.setText(_translate("Dialog", arr[4][3]))
        self.label_26.setText(_translate("Dialog", arr[4][4]))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
